### ISSUE TITLE
App crashes on Android 15 

### ISSUE THREAD

**Issue by shailantani** [Hamza417/Peristyle#72] opened 2024-09-11 13:33 UTC
Hi, I just downloaded the app (2.00 Alpha) and after giving the all files access, the app crashes.
Here's the log

[app.simple.peri_2024-09-11T19_01_15.794.log](https://github.com/user-attachments/files/16964319/app.simple.peri_2024-09-11T19_01_15.794.log)

**Comment by Hamza417** [comment] 2024-09-11 14:28
The log says AppOp is blocked for Peristyle, are you using any tool that blocks app ops?

**Comment by shailantani** [comment] 2024-09-11 16:11
> The log says AppOp is blocked for Peristyle, are you using any tool that blocks app ops?

Nope, using no app that blocks app permission. (I'm rooted though)
Anything more I can do to help with the error?

**Comment by Hamza417** [comment] 2024-09-11 16:13
> Anything more I can do to help with the error?

You can manually allow storage permission, if you are using Android 10+ you'll have to grant the all files access to the app, and you'll be good to go.

**Comment by Hamza417** [comment] 2024-09-11 16:49
Is it still crashing?

**Comment by shailantani** [comment] 2024-09-11 16:53
> Is it still crashing?

Yep, with the same error log :/

**Comment by Hamza417** [comment] 2024-09-11 17:02
> > Is it still crashing?
> 
> Yep, with the same error log :/

Try running this command using adb shell or any terminal of your choice

`appops set app.simple.peri READ_EXTERNAL_STORAGE allow`

What is your android version?

**Comment by shailantani** [comment] 2024-09-11 17:06
> > > Is it still crashing?
> > 
> > 
> > Yep, with the same error log :/
> 
> Try running this command using adb shell or any terminal of your choice
> 
> `appops set app.simple.peri READ_EXTERNAL_STORAGE allow`
> 
> What is your android version?
 Tried that, still crashing.
 
I'm running Android 15 QPR1 Beta 1.1 on Pixel 7a

**Comment by Hamza417** [comment] 2024-09-11 17:13
Reinstall the app

**Comment by shailantani** [comment] 2024-09-12 07:05
> Reinstall the app

nope, didn't work.
I think it has something to do with this:

https://issuetracker.google.com/issues/237124750

**Comment by Hamza417** [comment] 2024-09-15 09:29
It should be [intended behavior](https://developer.android.com/reference/android/app/WallpaperManager#getDrawable()) and should work unless there is some different underlying issue causing this.

**Comment by shailantani** [comment] 2024-09-16 02:33
> It should be [intended behavior](https://developer.android.com/reference/android/app/WallpaperManager#getDrawable()) and should work unless there is some different underlying issue causing this.

Hmm, so what could be the issue? Something with the app permission in Android 15?

**Comment by Astler** [comment] 2024-09-16 22:59
Same issue on my Pixel 8 Pro With Android 15 Beta 2. I was able to setup all file access and external memory folder with app setup screen. But after clicking continue, the app crashed with this error.

**Comment by Hamza417** [comment] 2024-09-17 04:49
Android 15 is still in Beta and Peristyle is only tested up to Android 14, they're maybe changing something in the 15, some new permissions restrictions maybe they do it all the time every year.

**Comment by Hamza417** [comment] 2024-09-18 04:44
I have found the source of the issue. It is caused by the same issue, they changed how the permissions work in Android 15, having All Files access doesn't get the system wallpaper anymore.

**Comment by Hamza417** [comment] 2024-09-18 05:14
[app-prod-release.zip](https://github.com/user-attachments/files/17038688/app-prod-release.zip)

The issue is fixed now, you can update the app using this APK and let me know if it works.

**Comment by shailantani** [comment] 2024-09-18 05:31
> [app-prod-release.zip](https://github.com/user-attachments/files/17038688/app-prod-release.zip)
> 
> The issue is fixed now, you can update the app using this APK and let me know if it works.

Hi! Thanks for the fix, but the app still seems to be crashing
But I think it's a different issue now 
Here's the log
[app.simple.peri_2024-09-18T10_59_36.970.log](https://github.com/user-attachments/files/17038830/app.simple.peri_2024-09-18T10_59_36.970.log)

**Comment by Hamza417** [comment] 2024-09-18 05:35
Does it need the combination of both? Can you also manually grant the MANAGE_EXTERNAL_STORAGE and see if it works?

**Comment by shailantani** [comment] 2024-09-18 05:43
> they changed how the permissions work in Android 15, having All Files access doesn't get the system wallpaper anymore.

Will try it out right away!

> Does it need the combination of both? Can you also manually grant the MANAGE_EXTERNAL_STORAGE and see if it works?

Would you know the adb command to manually grant the permission by any chance?

**Comment by Hamza417** [comment] 2024-09-18 05:45
> Would you know the adb command to manually grant the permission by any chance?

It should be this `appops set app.simple.peri MANAGE_EXTERNAL_STORAGE allow` or can manually search All Files in settings.

**Comment by shailantani** [comment] 2024-09-18 05:45
I just went to settings, and gave it all files access. and the app works now!
Thanks a lot

**Comment by Hamza417** [comment] 2024-09-18 05:49
This isn't fixed yet, but so far it's confirmed that you'd need both READ_MEDIA_IMAGES and MANAGE_EXTERNAL_STORAGE permission to access the system wallpapers. Both of them are really sensitive permissions and Android could have easily added GET_WALLPAPERS or something like that to make it easier for both developers and users, but here we are. I'm glad it worked, and the fix will be available in the next release.

**Comment by shailantani** [comment] 2024-09-18 05:51
> This isn't fixed yet, but so far it's confirmed that you'd need both READ_MEDIA_IMAGES and MANAGE_EXTERNAL_STORAGE permission to access the system wallpapers. Both of them are really sensitive permissions and Android could have easily added GET_WALLPAPERS or something like that to make it easier for both developers and users, but here we are. I'm glad it worked, and the fix will be available in the next release.

Yep, a very frustrating issue, I faced it with another app as well ://
Nevertheless, thanks for adding support for Android 15 as well, really appreciate it and love the app 👍

**Closed** 2024-09-18 05:53 UTC
Labels: error
