### ISSUE TITLE
App crashes on Android 9

### ISSUE THREAD

**Issue by thaihugo** [Hamza417/Peristyle#79] opened 2024-09-18 03:44 UTC
Hi,

I just wanted to report that V2 beta is also crashing on android 9  when clicking on the setup menu, for the first item to give file access. Clicking the item crashes the app, even if the file access right has been given manually. It is then not possible to use the program, as the initial setup is not letting the user continue. All other setup items are working as intended.

As a workaround, might it be possible that you do not force check the file access rights by letting the user continue even if all steps are not done properly by the setup process? 

Phone is Huawei MRD-LX1 mostly de-googled and de-huawei-ed. Not app has a similar issue on it. V1 version was working perfectly.

Thanks for your time and work

**Comment by Hamza417** [comment] 2024-09-18 04:00
This is a duplicate of the issue https://github.com/Hamza417/Peristyle/issues/72

**Comment by Hamza417** [comment] 2024-09-18 04:32
I found the issue, and it was indeed causing the crash when permission is requested. I have fixed the crash and various other related issues.

**Closed by Hamza417** 2024-09-18 04:32 UTC
Labels: bug, error
