### ISSUE TITLE
New Feature Request

### ISSUE THREAD

**Issue by 55ahmedsalah** [Hamza417/Peristyle#86] opened 2024-09-24 23:36 UTC
Thank for the wonderful app

Can you please add the option to change the wallpapers with every lock and unlock?

**Comment by Hamza417** [comment] 2024-09-25 03:03
It's not possible for the app to do so, I mean it is, but Android pretty much restarts the whole system when the wallpaper changes and doing that every unlock will overload the system. Also, it'd require the app to run all the time, which isn't good for the battery as well.

However, [you can look into this thread and create your own automation task or something to ask Peristyle to change wallpaper everything screen is unlocked](https://github.com/Hamza417/Peristyle/issues/22).

**Comment by Hamza417** [comment] 2024-09-25 03:04
_Duplicate of https://github.com/Hamza417/Peristyle/issues/23_

**Closed by Hamza417** 2024-09-25 03:04 UTC
Labels: duplicate
